/*
    t1 Comment
    t2 Account
    t3 Link
    t4 Message
    t5 Subreddit
    t6 Award 
*/
export interface Listing {
    kind: "Listing";
    data: {
        after: null,
        before: null,
        dist: number,
        geo_filter: string,
        modhash: string,
        children: Array<Thing>
    };
}
export interface Thing {
    kind: "t1" | "t2" | "t3" | "t4" | "t5" | "t6";
    data: {
        all_awardings: Array<unknown>,
        allow_live_comments?: boolean,
        approved_at_utc: number | null,
        approved_by: string | null,
        archived: boolean,
        associated_award?: string | null,
        author: string,
        author_flair_background_color: string | null,
        author_flair_css_class: string | null,
        author_flair_richtext: Array<unknown>,
        author_flair_template_id: string | null,
        author_flair_text: string | null,
        author_flair_text_color: string | null,
        author_flair_type: string,
        author_fullname: string,
        author_is_blocked: boolean,
        author_patreon_flair: boolean,
        athor_premium: boolean,
        awarders: Array<unknown>,
        banned_at_utc: number | null,
        banned_by: string | null,
        body?: string,
        body_html?: string,
        can_gild: boolean,
        can_mod_post: boolean,
        category?: string | null,
        collapsed?: boolean,
        collapsed_because_crowd_control?: boolean | null,
        collapsed_reason?: string | null,
        collapsed_reason_code?: number | null,
        comment_type?: string | null,
        controversiality?: number,
        clicked?: boolean,
        content_categories?: Array<string> | null,
        contest_mode?: boolean,
        created: number,
        created_utc: number,
        depth?: number,
        discussion_type?: string | null,
        distinguished: string | null,
        domain?: string,
        downs: number,
        edited: boolean,
        gilded: number,
        gildings: object,
        hidden?: boolean,
        hide_score?: boolean,
        id: string,
        is_submitter?: boolean,
        is_created_from_ads_ui?: boolean,
        is_crosspostable?: boolean,
        is_meta?: boolean,
        is_original_content?: boolean,
        is_reddit_media_domain?: boolean,
        is_robot_indexable?: boolean,
        is_self?: boolean,
        is_video?: boolean,
        likes: number | null,
        link_id?: string,
        link_flair_background_color?: string | null,
        link_flair_css_class?: string,
        link_flair_richtext?: Array<{
            e?: string,
            t?: string
        }>,
        link_flair_text?: string,
        link_flair_text_color?: string | null,
        link_flair_type?: string,
        locked: boolean,
        media?: {
            event_id?: string,
            type?: string,
        } | null,
        media_embed?: {
            content?: string,
            height?: number,
            scrolling?: boolean,
            width?: number,
        },
        media_only?: boolean,
        mod_note: string | null,
        mod_reason_by: string | null,
        mod_reason_title: string | null,
        mod_reports: Array<unknown>,
        name: string,
        no_follow: boolean,
        num_comments?: number,
        num_crossposts?: number,
        num_duplicates?: number,
        num_reports: number | null,
        parent_id?: string,
        over_18?: boolean,
        permalink: string,
        pinned?: boolean,
        post_hint?: string,
        preview?: {
            enabled: boolean,
            images: Array<{
                id: string,
                resolutions: Array<{
                    url: string,
                    height: number,
                    width: number,
                }>,
                source: {
                    url: string,
                },
                variants: {}
            }>
        },
        pwls?: number,
        quarantine?: boolean,
        removal_reason: string | null,
        replies?: {
            kind: "Listing",
            data: Listing,
        }
        removed_by?: string | null,
        removed_by_category?: string | null,
        report_reasons: Array<string> | null,
        saved: boolean,
        score: number,
        score_hidden?: boolean,
        secure_media?: {
            event_id?: string,
            type?: string,
        },
        secure_media_embed?: {
            content?: string,
            height?: number,
            media_domain_url?: string,
            scrolling?: boolean,
            width?: number,
        },
        selftext?: string,
        selftext_html?: string | null,
        send_replies: boolean,
        spoiler?: boolean,
        stickied: boolean,
        subreddit: string,
        subreddit_id: string,
        subreddit_name_prefixed: string,
        subreddit_subscribers?: number,
        subreddit_type: string,
        suggested_sort?: string,
        thumbnail?: string,
        thumbnail_height?: number,
        thumbnail_width?: number,
        title?: string,
        top_awarded_type: string | null,
        total_awards_received: number,
        treatment_tags: Array<string>,
        unrepliable_reason?: string | null,
        ups: number,
        upvote_ratio?: number,
        url?: string,
        url_overridden_by_dest?: string,
        user_reports: Array<string>,
        view_count?: number | null,
        visited?: boolean,
        wls?: number,
    }
}