/*
    t1 Comment
    t2 Account
    t3 Link
    t4 Message
    t5 Subreddit
    t6 Award 
*/
export interface Listing {
    kind: "Listing";
    data: {
        after: null,
        before: null,
        dist: number,
        geo_filter: string,
        modhash: string,
        children: Array<Thing>
    };
}

export type Thing = T1 | T2 | T3;

export interface T1 {
    kind: "t1";
    data: {
        "subreddit_id": string,
        "approved_at_utc": number | null,
        "author_is_blocked": boolean,
        "comment_type": string | null,
        "awarders": Array<string>,
        "mod_reason_by": string | null,
        "banned_by": string | null,
        "author_flair_type": "text",
        "total_awards_received": number,
        "subreddit": string,
        "author_flair_template_id": string | null,
        "likes": number | null,
        "replies": Listing,
        "user_reports": [],
        "saved": boolean,
        "id": string,
        "banned_at_utc": number | null,
        "mod_reason_title": string | null,
        "gilded": number,
        "archived": boolean,
        "collapsed_reason_code": number | null,
        "no_follow": boolean,
        "author": string,
        "can_mod_post": boolean,
        "created_utc": number,
        "send_replies": boolean,
        "parent_id": string,
        "score": number,
        "author_fullname": string,
        "removal_reason": string | number | null,
        "approved_by": string | null,
        "mod_note": string | null,
        "all_awardings": [],
        "body": string,
        "edited": boolean,
        "top_awarded_type": string | null,
        "author_flair_css_class": string | null,
        "name": string,
        "is_submitter": boolean,
        "downs": number,
        "author_flair_richtext": [],
        "author_patreon_flair": boolean,
        "body_html": string,
        "gildings": {

        },
        "collapsed_reason": string | null,
        "distinguished": boolean | null,
        "associated_award": unknown | null,
        "stickied": boolean,
        "author_premium": boolean,
        "can_gild": boolean,
        "link_id": string,
        "unrepliable_reason": string | null,
        "author_flair_text_color": string | null,
        "score_hidden": boolean,
        "permalink": string,
        "subreddit_type": "public" | "private",
        "locked": boolean,
        "report_reasons": unknown | null,
        "created": number,
        "author_flair_text": string | null,
        "treatment_tags": Array<string>,
        "collapsed": boolean,
        "subreddit_name_prefixed": string,
        "controversiality": number,
        "depth": number,
        "author_flair_background_color": string | null,
        "collapsed_because_crowd_control": unknown | null,
        "mod_reports": [],
        "num_reports": number | null,
        "ups": number
    };
};
export interface T2 {
    kind: "t2";
    data: {
        "is_employee": boolean,
        "is_friend": boolean,
        "subreddit": {
            "default_set": true,
            "user_is_contributor": false,
            "banner_img": string,
            "allowed_media_in_comments": Array<string>,
            "user_is_banned": boolean,
            "free_form_reports": boolean,
            "community_icon": string | null,
            "show_media": boolean,
            "icon_color": string,
            "user_is_muted": boolean | null,
            "display_name": string,
            "header_img": string | null,
            "title": string,
            "previous_names": Array<string>,
            "over_18": boolean,
            "icon_size": [number, number],
            "primary_color": string,
            "icon_img": string,
            "decription": string,
            "submit_link_label": string,
            "header_size": number | null,
            "restrict_posting": boolean,
            "restrict_commenting": boolean,
            "subscribers": number,
            "submit_text_label": string,
            "is_default_icon": boolean,
            "link_flair_position": string,
            "display_name_prefixed": string,
            "key_color": string,
            "name": string,
            "is_default_banner": boolean,
            "url": string,
            "quarantine": boolean,
            "banner_size": number | null,
            "user_is_moderator": boolean,
            "accept_followers": boolean,
            "public_description": string,
            "link_flair_enabled": boolean,
            "disable_contributor_request": boolean,
            "subreddit_type": "user",
            "user_is_subscriber": boolean,
        },
        "snoovatar_size": [number, number],
        "id": string,
        "verified": boolean,
        "is_gold": boolean,
        "is_mod": boolean,
        "awarder_karma": number,
        "has_verified_email": boolean,
        "icon_img": string,
        "hide_from_robots": boolean,
        "link_karma": number,
        "pref_show_snoovatar": boolean,
        "is_blocked": boolean,
        "total_karma": number,
        "accept_chats": boolean,
        "name": string,
        "created": number,
        "created_utc": number,
        "snoovatar_img": string,
        "comment_karma": number,
        "accept_followers": boolean,
        "has_subscribed": boolean,
        "accept_pms": boolean,
    };
};
export interface T3 {
    kind: "t3";
    data: {
        all_awardings: [],
        allow_live_comments: boolean,
        approved_at_utc: number | null,
        approved_by: string | null,
        archived: boolean,
        author: string,
        author_flair_background_color: string | null,
        author_flair_css_class: string | null,
        author_flair_richtext: [],
        author_flair_template_id: string | null,
        author_flair_text: string | null,
        author_flair_text_color: string | null,
        author_flair_type: "text",
        author_fullname: string,
        author_is_blocked: boolean,
        author_patreon_flair: boolean,
        author_premium: boolean,
        awarders: [],
        banned_at_utc: number | null,
        banned_by: string | null,
        can_gild: boolean,
        can_mod_post: boolean,
        category: string | null,
        clicked: boolean,
        content_categories: null,
        contest_mode: boolean,
        created: number,
        created_utc: number,
        discussion_type: string | null,
        distinguished: boolean | null,
        domain: string,
        downs: number,
        edited: boolean,
        gilded: number,
        gildings: {},
        hidden: boolean,
        hide_score: boolean,
        id: string,
        is_created_from_ads_ui: boolean,
        is_crosspostable: boolean,
        is_meta: boolean,
        is_original_content: boolean,
        is_reddit_media_domain: boolean,
        is_robot_indexable: boolean,
        is_self: boolean,
        is_video: boolean,
        likes: number | null,
        link_flair_background_color: string,
        link_flair_css_class: string | null,
        link_flair_richtext: [],
        link_flair_text: string | null,
        link_flair_text_color: string | null,
        link_flair_type: "text",
        locked: boolean,
        media: {
            oembed: {
                author_name: string,
                author_url: string,
                height: number,
                html: string,
                provider_name: string,
                provider_url: string,
                thumbnail_height: number,
                thumbnail_url: string,
                thumbnail_width: number,
                title: string,
                type: string,
                version: string,
                width: number,
            }
            type: string,
        },
        media_embed: {
            content: string,
            height: number,
            scrolling: boolean,
            width: number,
        },
        media_only: boolean,
        mod_note: string | null,
        mod_reason_by: string | null,
        mod_reason_title: string | null,
        mod_reports: [],
        name: string,
        no_follow: boolean,
        num_comments: number,
        num_crossposts: number,
        num_reports: number | null,
        over_18: boolean,
        permalink: string,
        pinned: boolean,
        post_hint: string,
        preview: {
            enabled: boolean,
            images: Array<{
                id: string,
                resolutions: Array<{
                    height: number,
                    url: string,
                    width: number,
                }>,
                source: {
                    url: string,
                    height: number,
                    width: number,
                },
                variants: {}

            }>
        },
        pwls: number,
        quarantine: boolean,
        removal_reason: string | null,
        removed_by: string | null,
        removed_by_category: string | null,
        report_reasons: Array<string> | null,
        saved: boolean,
        score: number,
        secure_media: {
            oembed: {
                author_name: string,
                author_url: string,
                height: number,
                html: string,
                provider_name: string,
                provider_url: string,
                thumbnail_height: number,
                thumbnail_url: string,
                thumbnail_width: number,
                title: string,
                type: string,
                version: string,
                width: number,
            },
            type: string,
        },
        secure_media_embed: {
            content: string,
            height: number,
            media_domain_url: string,
            scrolling: boolean,
            width: number,
        },
        selftext: string,
        selftext_html: string,
        send_replies: boolean,
        spoiler: boolean,
        stickied: boolean,
        subreddit: string,
        subreddit_id: string,
        subreddit_name_prefixed: string,
        subreddit_subscribers: number,
        subreddit_type: "public" | "private",
        suggested_sort: string | null,
        thumbnail: string,
        thumbnail_height: number,
        thumbnail_width: number,
        title: string,
        top_awarded_type: string | null,
        total_awards_received: number,
        treatment_tags: Array<string>,
        ups: number,
        upvote_ratio: number,
        url: string,
        url_overridden_by_dest: string,
        user_reports: Array<unknown>,
        view_count: number | null,
        visited: boolean,
        wls: number,
    };
};