import {describe, expect, test} from '@jest/globals';
import fetchMock from "fetch-mock-jest";
import mockAsyncHandler from "./mockFetch";


describe("(URL: ✓, method: 'GET', payload: X)", () => {
    test('Returns Community posts in an Array', async () => {
        
        // Setting
        const url = "worldnews.json";
        const data = [     
            {      
              author: 'WorldNewsMods',
              author_fullname: 't2_glrsi',
              created_utc: 1717909358,
              downs: 0,
              id: '1dblx3l',
              name: 't3_1dblx3l',
              num_comments: 174,
              permalink: '/r/worldnews/comments/1dblx3l/rworldnews_live_thread_russian_invasion_of/',
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: '/r/WorldNews Live Thread: Russian Invasion of Ukraine Day 837, Part 1 (Thread #983)',   
              ups: 704,
              url: 'https://www.reddit.com/live/18hnzysb1elcs'
            },
            {
              author: 'AutoModerator',
              author_fullname: 't2_6l4z3',
              created_utc: 1717913641,
              downs: 0,
              id: '1dbn1ci',
              name: 't3_1dbn1ci',
              num_comments: 334,
              permalink: '/r/worldnews/comments/1dbn1ci/rworldnews_live_thread_for_israelhamas_war_thread/',  
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: '/r/WorldNews Live Thread for Israel-Hamas War (Thread #53)',
              ups: 102,
              url: 'https://www.reddit.com/live/1bsso361afr0r'
            },
            {
              author: 'Current-Bridge-9422',
              author_fullname: 't2_fbfnc79j',
              created_utc: 1717926773,
              downs: 0,
              id: '1dbq6e1',
              name: 't3_1dbq6e1',
              num_comments: 615,
              permalink: '/r/worldnews/comments/1dbq6e1/hostages_father_dies_hours_before_his_rescue/',       
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: "Hostage's father dies hours before his rescue.",
              ups: 4641,
              url: 'https://www.jns.org/hostages-father-dies-hours-before-his-rescue/'
            },
            {
              author: 'Master_Jackfruit3591',
              author_fullname: 't2_s5uk227fv',
              created_utc: 1717940764,
              downs: 0,
              id: '1dbu3kd',
              name: 't3_1dbu3kd',
              num_comments: 113,
              permalink: '/r/worldnews/comments/1dbu3kd/report_journalist_doctor_held_noa_argamani/',
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: 'Report: Journalist, doctor held Noa Argamani hostage in Gaza',
              ups: 1225,
              url: 'https://www.jns.org/report-journalist-doctor-held-noa-argamani-hostage-in-gaza/'
            },
            {
              author: 'HenzShuyi',
              author_fullname: 't2_pea6ti3f',
              created_utc: 1717920268,
              downs: 0,
              id: '1dbonqu',
              name: 't3_1dbonqu',
              num_comments: 253,
              permalink: '/r/worldnews/comments/1dbonqu/russia_is_sending_young_africans_to_die_in_its/',     
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: 'Russia Is Sending Young Africans to Die in Its War Against Ukraine',
              ups: 2929,
              url: 'https://www.bloomberg.com/news/articles/2024-06-09/russia-ukraine-war-africans-forced-to-fight-and-die-for-the-kremlin'
            },
            {
              author: 'Brandolf_o',
              author_fullname: 't2_7pyx4snyk',
              created_utc: 1717925898,
              downs: 0,
              id: '1dbpz78',
              name: 't3_1dbpz78',
              num_comments: 76,
              permalink: '/r/worldnews/comments/1dbpz78/ukraine_says_latestgeneration_russian_fighter_jet/',  
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: 'Ukraine says latest-generation Russian fighter jet hit for first time',
              ups: 1330,
              url: 'https://www.reuters.com/world/europe/ukraine-says-latest-generation-russian-fighter-jet-hit-first-time-2024-06-09/'
            },
            {
              author: 'Red_Franklin',
              author_fullname: 't2_bp0z313qp',
              created_utc: 1717909318,
              downs: 0,
              id: '1dblwq0',
              name: 't3_1dblwq0',
              num_comments: 292,
              permalink: '/r/worldnews/comments/1dblwq0/only_half_chinese_china_refused_to_help_secure/',     
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: "'Only half Chinese': China refused to help secure release of Noa Argamani",
              ups: 2943,
              url: 'https://www.ynetnews.com/article/bjx7jxgbc'
            },
            {
              author: 'Infidel8',
              author_fullname: 't2_ipqi1',
              created_utc: 1717880025,
              downs: 0,
              id: '1dbck0s',
              name: 't3_1dbck0s',
              num_comments: 2385,
              permalink: '/r/worldnews/comments/1dbck0s/russia_declares_us_as_enemy_state_for_first_time/',   
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: 'Russia Declares US As Enemy State For First Time Amid Deteriorating Ties Over Ukraine', 
              ups: 27107,
              url: 'https://www.india.com/news/world/russia-declares-us-as-enemy-state-for-first-time-in-diplomatic-history-amid-deteriorating-ties-over-ukraine-6996573/'
            },
            {
              author: 'FuryVisionWanda',
              author_fullname: 't2_qv1hb0o1c',
              created_utc: 1717941940,
              downs: 0,
              id: '1dbuid6',
              name: 't3_1dbuid6',
              num_comments: 57,
              permalink: '/r/worldnews/comments/1dbuid6/iran_bought_300_tons_uranium_from_niger_for/',        
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: 'Iran bought 300 tons uranium from Niger for illicit nuke weapon program - report',      
              ups: 394,
              url: 'https://www.jpost.com/middle-east/iran-news/article-805535'
            },
            {
              author: 'Comprehensive-Gas832',
              author_fullname: 't2_cf3j6yqg',
              created_utc: 1717935967,
              downs: 0,
              id: '1dbski2',
              name: 't3_1dbski2',
              num_comments: 50,
              permalink: '/r/worldnews/comments/1dbski2/supersonic_physicists_rounded_up_as_spies_in/',       
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: 'Supersonic physicists rounded up as spies in Russia ',
              ups: 524,
              url: 'https://www.bbc.com/news/articles/c8001gvp4dpo'
            },
            {
              author: 'duckanroll',
              author_fullname: 't2_zpmfo',
              created_utc: 1717928444,
              downs: 0,
              id: '1dbqktp',
              name: 't3_1dbqktp',
              num_comments: 26,
              permalink: '/r/worldnews/comments/1dbqktp/ukrainian_military_claims_to_have_destroyed_one/',    
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: 'Ukrainian military claims to have destroyed one of Russia’s most advanced fighter jets',        ups: 655,
              url: 'https://novayagazeta.eu/articles/2024/06/09/ukrainian-military-claims-to-have-destroyed-one-of-russias-most-advanced-fighter-jets-en-news'
            },
            {
              author: 'AgentBlue62',
              author_fullname: 't2_3pp4e753',
              created_utc: 1717932606,
              downs: 0,
              id: '1dbrm5i',
              name: 't3_1dbrm5i',
              num_comments: 11,
              permalink: '/r/worldnews/comments/1dbrm5i/ukraine_claims_its_hit_a_russian_su57_fighter/',      
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: "Ukraine claims it's hit a Russian Su-57 fighter plane for first time",
              ups: 357,
              url: 'https://www.euronews.com/2024/06/09/ukraine-claims-its-hit-a-russian-su-57-fighter-plane-for-first-time'
            },
            {
              author: 'BezugssystemCH1903',
              author_fullname: 't2_bamjgcg8',
              created_utc: 1717933763,
              downs: 0,
              id: '1dbrxlz',
              name: 't3_1dbrxlz',
              num_comments: 23,
              permalink: '/r/worldnews/comments/1dbrxlz/hate_symbols_banned_by_voters_in_geneva/',
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: 'Hate symbols banned by voters in Geneva',
              ups: 277,
              url: 'https://www.swissinfo.ch/eng/democracy/hate-symbols-banned-by-voters-in-geneva/80152669?utm_source=multiple&amp;utm_medium=website&amp;utm_campaign=news_en&amp;utm_content=o&amp;utm_term=wpblock_highlighted-compact-news-carousel'
            },
            {
              author: '-ForDisplayOnly',
              author_fullname: 't2_11xrms3y',
              created_utc: 1717937153,
              downs: 0,
              id: '1dbsx5n',
              name: 't3_1dbsx5n',
              num_comments: 61,
              permalink: '/r/worldnews/comments/1dbsx5n/north_korea_sends_another_wave_of_trash_balloons/',   
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: 'North Korea sends another wave of trash balloons into South Korea | CNN',
              ups: 200,
              url: 'https://amp.cnn.com/cnn/2024/06/09/asia/north-korea-balloons-response-intl-hnk'
            },
            {
              author: '_A_Monkey',
              author_fullname: 't2_922eal3f',
              created_utc: 1717872621,
              downs: 0,
              id: '1db9v57',
              name: 't3_1db9v57',
              num_comments: 394,
              permalink: '/r/worldnews/comments/1db9v57/35_children_among_those_killed_in_latest_sudan/',     
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: '35 children among those killed in latest Sudan civil war carnage, U.N. says',
              ups: 4618,
              url: 'https://www.cbsnews.com/amp/news/sudan-civil-war-army-alleges-rsf-massacre-in-wad-al-noora/'
            },
            {
              author: 'Ok-Lets-Talk-It-Out',
              author_fullname: 't2_j3vlx8z0g',
              created_utc: 1717889572,
              downs: 0,
              id: '1dbfwpl',
              name: 't3_1dbfwpl',
              num_comments: 306,
              permalink: '/r/worldnews/comments/1dbfwpl/us_intelligence_aided_israeli_hostage_rescue/',       
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: 'U.S. intelligence aided Israeli hostage rescue',
              ups: 1846,
              url: 'https://www.washingtonpost.com/national-security/2024/06/08/us-intelligence-israeli-hostage-rescue-gaza/'
            },
            {
              author: 'Skippernutts',
              author_fullname: 't2_623tvo2s',
              created_utc: 1717909474,
              downs: 0,
              id: '1dbly96',
              name: 't3_1dbly96',
              num_comments: 58,
              permalink: '/r/worldnews/comments/1dbly96/66_of_young_south_koreans_dependent_on_parents/',     
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: '66% of young South Koreans dependent on parents',
              ups: 624,
              url: 'https://www.koreatimes.co.kr/www/biz/2024/06/126_376112.html'
            },
            {
              author: 'ConsciousStop',
              author_fullname: 't2_2rwrdl81',
              created_utc: 1717941154,
              downs: 0,
              id: '1dbu8bn',
              name: 't3_1dbu8bn',
              num_comments: 47,
              permalink: '/r/worldnews/comments/1dbu8bn/sextortion_is_the_fastestgrowing_scam_affecting/',    
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: 'Sextortion is the fastest-growing scam affecting teenagers globally',
              ups: 119,
              url: 'https://www.bbc.co.uk/news/articles/c2llzppyx05o'
            },
            {
              author: 'riwnodennyk',
              author_fullname: 't2_cm8zf',
              created_utc: 1717927264,
              downs: 0,
              id: '1dbqang',
              name: 't3_1dbqang',
              num_comments: 11,
              permalink: '/r/worldnews/comments/1dbqang/ukraine_hits_russian_su57_jet_for_first_time/',       
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: 'Ukraine hits Russian Su-57 jet for first time, military intelligence says',
              ups: 247,
              url: 'https://kyivindependent.com/hur-ukraine-hit-su-57-jet-for-first-time/'
            },
            {
              author: 'Alien_P3rsp3ktiv',
              author_fullname: 't2_djh3s2dv',
              created_utc: 1717858729,
              downs: 0,
              id: '1db4twf',
              name: 't3_1db4twf',
              num_comments: 405,
              permalink: '/r/worldnews/comments/1db4twf/norway_wealth_fund_to_vote_against_musks_56/',        
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: "Norway wealth fund to vote against Musk's $56 billion Tesla pay package",
              ups: 8372,
              url: 'https://www.reuters.com/technology/norway-wealth-fund-vote-against-musks-56-bln-tesla-pay-package-2024-06-08/'
            },
            {
              author: 'rationaleworking',
              author_fullname: 't2_tdl6rfl8s',
              created_utc: 1717876577,
              downs: 0,
              id: '1dbbbq0',
              name: 't3_1dbbbq0',
              num_comments: 174,
              permalink: '/r/worldnews/comments/1dbbbq0/un_confirms_11_staff_detained_by_houthis_in_yemen/',  
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: 'UN confirms 11 staff detained by Houthis in Yemen',
              ups: 2828,
              url: 'https://www.bbc.com/news/articles/cgxxlgevevwo'
            },
            {
              author: 'ubcstaffer123',
              author_fullname: 't2_in26fpu8c',
              created_utc: 1717888265,
              downs: 0,
              id: '1dbfghn',
              name: 't3_1dbfghn',
              num_comments: 327,
              permalink: '/r/worldnews/comments/1dbfghn/putins_daughters_make_rare_appearance_at_st/',        
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: 'Putin’s daughters make rare appearance at St. Petersburg economic forum',
              ups: 1476,
              url: 'https://www.cnn.com/2024/06/08/world/putins-daughters-rare-appearance-st-petersburg-intl/index.html'
            },
            {
              author: 'Master-Concept-5260',
              author_fullname: 't2_xic6p7bqm',
              created_utc: 1717866890,
              downs: 0,
              id: '1db7s02',
              name: 't3_1db7s02',
              num_comments: 510,
              permalink: '/r/worldnews/comments/1db7s02/hostages_held_alongside_families_in_adjacent/',       
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: 'Hostages held alongside families in adjacent buildings | new details and first footage',        ups: 4163,
              url: 'https://www.ynetnews.com/article/bycfb11gbr#autoplay'
            },
            {
              author: 'BubsyFanboy',
              author_fullname: 't2_1t3qre66',
              created_utc: 1717938581,
              downs: 0,
              id: '1dbtd9a',
              name: 't3_1dbtd9a',
              num_comments: 11,
              permalink: '/r/worldnews/comments/1dbtd9a/russia_deploys_additional_forces_on_the_border/',     
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: 'Russia deploys additional forces on the border with Ukraine’s Kharkiv',
              ups: 95,
              url: 'https://tvpworld.com/77983745/russia-deploys-additional-forces-on-the-border-with-ukraines-kharkiv'
            },
            {
              author: 'SpectralShadowX',
              author_fullname: 't2_p68ldeey2',
              created_utc: 1717852450,
              downs: 0,
              id: '1db2pi9',
              name: 't3_1db2pi9',
              num_comments: 1300,
              permalink: '/r/worldnews/comments/1db2pi9/we_will_not_surrender_hamas_leader_ismail_haniyeh/',  
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: "'We will not surrender': Hamas leader Ismail Haniyeh fumes after Israel frees hostages",        ups: 9108,
              url: 'https://www.jpost.com/breaking-news/article-805433'
            },
            {
              author: 'itslalala',
              author_fullname: 't2_ocvx2',
              created_utc: 1717843094,
              downs: 0,
              id: '1db01as',
              name: 't3_1db01as',
              num_comments: 2573,
              permalink: '/r/worldnews/comments/1db01as/idf_rescues_hostages_noa_argamani_andrey_kozlov/',    
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: 'IDF rescues hostages Noa Argamani, Andrey Kozlov, Shlomi Ziv, and Almog Meir',
              ups: 19483,
              url: 'https://www.jpost.com/breaking-news/article-805424'
            },
            {
              author: 'Serious_Journalist14',
              author_fullname: 't2_6ipoekrb',
              created_utc: 1717854045,
              downs: 0,
              id: '1db382a',
              name: 't3_1db382a',
              num_comments: 320,
              permalink: '/r/worldnews/comments/1db382a/idf_successfully_eliminates_senior_hamas_general/',   
              selftext: '',
              selftext_html: null,
              subreddit: 'worldnews',
              subreddit_id: 't5_2qh13',
              subreddit_name_prefixed: 'r/worldnews',
              title: 'IDF successfully eliminates senior Hamas General Security Forces commander',
              ups: 5582,
              url: 'https://www.jpost.com/breaking-news/article-805392'
            }
        ]
        
        fetchMock.mock("https://www.reddit.com/r/worldnews.json", data)
        // Test
        const body = await mockAsyncHandler(url, "GET");

        // Result
        //expect(fetchMock).toBeDefined()
        expect(body).toEqual(data)
    });
})

